language: java
jdk:
  - oraclejdk8
before_script:
  mysql -e 'CREATE TABLE IF NOT EXISTS activity(id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, active TINYINT(1) DEFAULT NULL, created_at TIMESTAMP DEFAULT NOW())'